{
 "title": "NodeGraph",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Blast radius",
   "type": "nodeGraph",
   "gridPos": { "h": 10, "w": 14, "x": 5, "y": 0 },
   "targets": [
    { "expr": "sort(nodegraph_node_info)", "legendFormat": "__auto" },
    { "expr": "sort(nodegraph_edge_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(prober_probe_duration_seconds_bucket{namespace=\"nodes\"}[1m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{namespace=\"nodes\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}