apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-graph-exporter-sm
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: node-graph-exporter
  endpoints:
  - port: http
    interval: 1s
