# Imagen ligera de Python
FROM python

# Crear carpeta de la app
WORKDIR /app

# Copiar el código
COPY app.py /app/

# Exponer un puerto (ej: 5000)
EXPOSE 5000

# Ejecutar el script por defecto
CMD ["python", "app.py"]
