apiVersion: v1
kind: Service
metadata:
  name: node1
spec:
  selector: { app: node1 }
  ports:
    - name: http
      port: 5000
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: node2
spec:
  selector: { app: node2 }
  ports:
    - name: http
      port: 5000
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: node3
spec:
  selector: { app: node3 }
  ports:
    - name: http
      port: 5000
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: node4
spec:
  selector: { app: node4 }
  ports:
    - name: http
      port: 5000
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: node5
spec:
  selector: { app: node5 }
  ports:
    - name: http
      port: 5000
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: node6
spec:
  selector: { app: node6 }
  ports:
    - name: http
      port: 5000
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: node7
spec:
  selector: { app: node7 }
  ports:
    - name: http
      port: 5000
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: node8
spec:
  selector: { app: node8 }
  ports:
    - name: http
      port: 5000
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: node9
spec:
  selector: { app: node9 }
  ports:
    - name: http
      port: 5000
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: node10
spec:
  selector: { app: node10 }
  ports:
    - name: http
      port: 5000
      targetPort: 5000
