apiVersion: v1
kind: Service
metadata:
  name: node1
spec:
  selector:
    app: node1
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  clusterIP: None  # Headless para permitir resolución DNS directa por nombre
