apiVersion: apps/v1
kind: Deployment
metadata:
  name: node1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node1
  template:
    metadata:
      labels:
        app: node1
    spec:
      containers:
      - name: node1
        image: docker.io/adrian248/app:latest
        env:
        - name: PORT
          value: "5000"
        - name: PEERS
          value: "node2:5000"
        - name: DESTINOS
          value: "node8"
        - name: ROUTES
          value: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node2
  template:
    metadata:
      labels:
        app: node2
    spec:
      containers:
      - name: node2
        image: docker.io/adrian248/app:latest
        env:
        - name: PORT
          value: "5000"
        - name: PEERS
          value: "node1:5000,node4:5000,node6:5000,node5:5000,node10:5000"
        - name: DESTINOS
          value: "node7"
        - name: ROUTES
          value: "node3:node4:5000,node8:node6:5000,node9:node5:5000,node7:node6:5000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node3
  template:
    metadata:
      labels:
        app: node3
    spec:
      containers:
      - name: node3
        image: docker.io/adrian248/app:latest
        env:
        - name: PORT
          value: "5000"
        - name: PEERS
          value: "node4:5000,node6:5000"
        - name: DESTINOS
          value: ""
        - name: ROUTES
          value: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node4
  template:
    metadata:
      labels:
        app: node4
    spec:
      containers:
      - name: node4
        image: docker.io/adrian248/app:latest
        env:
        - name: PORT
          value: "5000"
        - name: PEERS
          value: "node3:5000,node2:5000"
        - name: DESTINOS
          value: ""
        - name: ROUTES
          value: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node5
  template:
    metadata:
      labels:
        app: node5
    spec:
      containers:
      - name: node5
        image: docker.io/adrian248/app:latest
        env:
        - name: PORT
          value: "5000"
        - name: PEERS
          value: "node2:5000,node9:5000,node6:5000"
        - name: DESTINOS
          value: ""
        - name: ROUTES
          value: "node10:node9:5000,node1:node2:5000,node4:node2:5000,node3:node6:5000,node7:node9:5000,node8:node6:5000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node6
  template:
    metadata:
      labels:
        app: node6
    spec:
      containers:
      - name: node6
        image: docker.io/adrian248/app:latest
        env:
        - name: PORT
          value: "5000"
        - name: PEERS
          value: "node2:5000,node3:5000,node5:5000,node7:5000,node8:5000"
        - name: DESTINOS
          value: ""
        - name: ROUTES
          value: "node9:node5:5000,node10:node2:5000,node1:node2:5000,node4:node3:5000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node7
  template:
    metadata:
      labels:
        app: node7
    spec:
      containers:
      - name: node7
        image: docker.io/adrian248/app:latest
        env:
        - name: PORT
          value: "5000"
        - name: PEERS
          value: "node6:5000,node8:5000,node9:5000"
        - name: DESTINOS
          value: ""
        - name: ROUTES
          value: "node1:node6:5000,node2:node6:5000,node3:node6:5000,node4:node6:5000,node5:node9:5000,node10:node9:5000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node8
  template:
    metadata:
      labels:
        app: node8
    spec:
      containers:
      - name: node8
        image: docker.io/adrian248/app:latest
        env:
        - name: PORT
          value: "5000"
        - name: PEERS
          value: "node7:5000,node6:5000"
        - name: DESTINOS
          value: ""
        - name: ROUTES
          value: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node9
  template:
    metadata:
      labels:
        app: node9
    spec:
      containers:
      - name: node9
        image: docker.io/adrian248/app:latest
        env:
        - name: PORT
          value: "5000"
        - name: PEERS
          value: "node10:5000,node5:5000,node7:5000"
        - name: DESTINOS
          value: "node4"
        - name: ROUTES
          value: "node1:node10:5000,node2:node5:5000,node3:node5:5000,node4:node5:5000,node6:node7:5000,node8:node7:5000"


apiVersion: apps/v1
kind: Deployment
metadata:
  name: node10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node10
  template:
    metadata:
      labels:
        app: node10
    spec:
      containers:
      - name: node10
        image: docker.io/adrian248/app:latest
        env:
        - name: PORT
          value: "5000"
        - name: PEERS
          value: "node2:5000,node9:5000"
        - name: DESTINOS
          value: ""
        - name: ROUTES
          value: ""
