version: "3.8"

services:
  nodo1:
    build: .
    container_name: nodo1
    environment:
      - NODE_NAME=nodo1
      - PORT=5000
      - METRICS_PORT=8000
      - PEERS=nodo2:5001,nodo3:5002
    networks:
      - red_p2p

  nodo2:
    build: .
    container_name: nodo2
    environment:
      - NODE_NAME=nodo2
      - PORT=5001
      - METRICS_PORT=8001
      - PEERS=nodo1:5000,nodo3:5002
    networks:
      - red_p2p

  nodo3:
    build: .
    container_name: nodo3
    environment:
      - NODE_NAME=nodo3
      - PORT=5002
      - METRICS_PORT=8002
      - PEERS=nodo1:5000,nodo2:5001
    networks:
      - red_p2p

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - red_p2p

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - red_p2p

networks:
  red_p2p:
    driver: bridge
