# Generates a TCP network following the topology described in: /networking/docs/network_topology.jpg.
# Uses ivancedo/tcp-network-main image.

services:
  node1:
    image: ivancedo/tcp-node-main
    hostname: node1
    environment:
      - PORT=5000
      - PEERS=node2:5000
      - DESTINOS=
      - ROUTES=
    volumes:
        - ../app:/app

  node2:
    image: ivancedo/tcp-node-main
    hostname: node2
    environment:
      - PORT=5000
      - PEERS=node1:5000,node4:5000,node6:5000,node5:5000,node10:5000
      - DESTINOS=
      - ROUTES=node3:node4:5000,node8:node6:5000,node9:node5:5000,node7:node6:5000
    volumes:
        - ../app:/app
  

  node3:
    image: ivancedo/tcp-node-main
    hostname: node3
    environment:
      - PORT=5000
      - PEERS=node4:5000,node6:5000
      - DESTINOS=
      - ROUTES=node1:node4:5000,node2:node4:5000,node5:node6:5000,node7:node6:5000,node8:node6:5000,node9:node6:5000,node10:node4:5000
    volumes:
        - ../app:/app
  

  node4:
    image: ivancedo/tcp-node-main
    hostname: node4
    environment:
      - PORT=5000
      - PEERS=node3:5000,node2:5000
      - DESTINOS=
      - ROUTES=node1:node2:5000,node5:node2:5000,node6:node3:5000,node7:node3:5000,node8:node3:5000,node9:node3:5000,node10:node2:5000
    volumes:
        - ../app:/app

  node5:
    image: ivancedo/tcp-node-main
    hostname: node5
    environment:
      - PORT=5000
      - PEERS=node2:5000,node9:5000,node6:5000
      - DESTINOS=
      - ROUTES=node10:node9:5000,node1:node2:5000,node4:node2:5000,node3:node6:5000,node7:node9:5000,node8:node6:5000
    volumes:
        - ../app:/app


  node6:
    image: ivancedo/tcp-node-main
    hostname: node6
    environment:
      - PORT=5000
      - PEERS=node2:5000,node3:5000,node5:5000,node7:5000,node8:5000
      - DESTINOS=
      - ROUTES=node9:node5:5000,node10:node2:5000,node1:node2:5000,node4:node3:5000
    volumes:
        - ../app:/app

  node7:
    image: ivancedo/tcp-node-main
    hostname: node7
    environment:
      - PORT=5000
      - PEERS=node6:5000,node8:5000,node9:5000
      - DESTINOS=
      - ROUTES=node1:node6:5000,node2:node6:5000,node3:node6:5000,node4:node6:5000,node5:node9:5000,node10:node9:5000
    volumes:
        - ../app:/app

  node8:
    image: ivancedo/tcp-node-main
    hostname: node8
    environment:
      - PORT=5000
      - PEERS=node7:5000,node6:5000
      - DESTINOS=
      - ROUTES=node1:node6:5000,node2:node6:5000,node3:node6:5000,node4:node6:5000,node5:node6:5000,node9:node7:5000,node10:node7:5000
    volumes:
        - ../app:/app

  node9:
    image: ivancedo/tcp-node-main
    hostname: node9
    environment:
      - PORT=5000
      - PEERS=node10:5000,node5:5000,node7:5000
      - DESTINOS=node4
      - ROUTES=node1:node10:5000,node2:node5:5000,node3:node5:5000,node4:node5:5000,node6:node7:5000,node8:node7:5000
    volumes:
        - ../app:/app
  
  node10:
    image: ivancedo/tcp-node-main
    hostname: node10
    environment:
      - PORT=5000
      - PEERS=node2:5000,node9:5000
      - DESTINOS=
      - ROUTES=node1:node2:5000,node4:node2:5000,node3:node2:5000,node5:node9:5000,node6:node2:5000,node7:node9:5000,node8:node9:5000
    volumes:
        - ../app:/app
  
