version: "3.8"

services:
  nodo1:
    build: .
    environment:
      - NODE_NAME=nodo1
      - PORT=5000
      - PEERS=nodo2:5000
    networks:
      - red_p2p

  nodo2:
    build: .
    environment:
      - NODE_NAME=nodo2
      - PORT=5000
      - PEERS=nodo3:5000,nodo4:5000
    networks:
      - red_p2p

  nodo3:
    build: .
    environment:
      - NODE_NAME=nodo3
      - PORT=5000
      - PEERS=nodo5:5000,nodo7:5000
    networks:
      - red_p2p

  nodo4:
    build: .
    environment:
      - NODE_NAME=nodo4
      - PORT=5000
      - PEERS=nodo5:5000,nodo6:5000
    networks:
      - red_p2p

  nodo5:
    build: .
    environment:
      - NODE_NAME=nodo5
      - PORT=5000
      - PEERS=
    networks:
      - red_p2p

  nodo6:
    build: .
    environment:
      - NODE_NAME=nodo6
      - PORT=5000
      - PEERS=nodo8:5000
    networks:
      - red_p2p

  nodo7:
    build: .
    environment:
      - NODE_NAME=nodo7
      - PORT=5000
      - PEERS=nodo8:5000
    networks:
      - red_p2p

  nodo8:
    build: .
    environment:
      - NODE_NAME=nodo8
      - PORT=5000
      - PEERS=nodo9:5000,nodo10:5000
    networks:
      - red_p2p

  nodo9:
    build: .
    environment:
      - NODE_NAME=nodo9
      - PORT=5000
      - PEERS=
    networks:
      - red_p2p

  nodo10:
    build: .
    environment:
      - NODE_NAME=nodo10
      - PORT=5000
      - PEERS=
    networks:
      - red_p2p

networks:
  red_p2p:
    driver: bridge
