services:
  server:
    build: ./node
    container_name: server
    networks:
    - net_client-1_server
    volumes:
    - ./configs/server.json:/app/config.json
  client-1:
    build: ./node
    container_name: client-1
    networks:
    - net_client-1_client-2
    - net_client-1_server
    volumes:
    - ./configs/client-1.json:/app/config.json
  client-2:
    build: ./node
    container_name: client-2
    networks:
    - net_client-1_client-2
    volumes:
    - ./configs/client-2.json:/app/config.json
  client-3:
    build: ./node
    container_name: client-3
    networks:
    - net_client-2_client-3
    volumes:
    - ./configs/client-3.json:/app/config.json
networks:
  net_client-1_server:
    driver: bridge
  net_client-1_client-2:
    driver: bridge
  net_client-2_client-3:
    driver: bridge
