services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    environment:
      - NODE_NAME=server
      - NODE_PORT=9000
      - PEER_NODES=client:9001
      - DELAY=10
    networks:
      custom_net:
        ipv4_address: 172.20.0.2

  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    environment:
      - NODE_NAME=client
      - NODE_PORT=9001
      - PEER_NODES=server:9000
      - DELAY=5
    networks:
      custom_net:
        ipv4_address: 172.20.0.3

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
